import React, { useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { useTheme } from '../context/ThemeContext';
import { RasterService } from '../types';
import { uid } from '../lib/geo';

export default function RasterServicesModal({ visible, services, onChange, onClose }: { visible: boolean; services: RasterService[]; onChange: (x: RasterService[]) => void; onClose: () => void }) {
 const { palette } = useTheme(); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [layers, setLayers] = useState(''); const [type, setType] = useState<'WMS'|'WMTS'|'XYZ'>('WMS');
 const add = () => { if (!url.trim()) return Alert.alert('الرابط مطلوب', 'أدخل رابط WMS أو WMTS أو XYZ.'); onChange([...services, { id: uid(), name: name.trim() || `${type} source`, url: url.trim(), layers: layers.trim() || undefined, type, enabled: true, opacity: .75, cacheEnabled: true }]); setName(''); setUrl(''); setLayers(''); };
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={[styles.sheet,{backgroundColor:palette.card,borderColor:palette.border}]}><View style={styles.header}><Pressable onPress={onClose}><Ionicons name="close" size={24} color={palette.textMuted}/></Pressable><Text style={[styles.title,{color:palette.text}]}>WMS / WMTS Sources & Offline Cache</Text></View><View style={styles.types}>{(['WMS','WMTS','XYZ'] as const).map((x)=><Pressable key={x} onPress={()=>setType(x)} style={[styles.type,{borderColor:type===x?palette.primary:palette.border,backgroundColor:type===x?palette.primary+'22':palette.bgElevated}]}><Text style={{color:palette.text,fontWeight:'800'}}>{x}</Text></Pressable>)}</View><TextInput value={name} onChangeText={setName} placeholder="اسم المصدر" placeholderTextColor={palette.textMuted} style={[styles.input,{color:palette.text,borderColor:palette.border}]}/><TextInput value={url} onChangeText={setUrl} placeholder={type==='WMS'?'https://server/ows':'https://server/tiles/{z}/{x}/{y}.png'} placeholderTextColor={palette.textMuted} style={[styles.input,{color:palette.text,borderColor:palette.border}]}/>{type==='WMS'&&<TextInput value={layers} onChangeText={setLayers} placeholder="Layers (مثال: imagery)" placeholderTextColor={palette.textMuted} style={[styles.input,{color:palette.text,borderColor:palette.border}]}/>}<Pressable onPress={add} style={[styles.primary,{backgroundColor:palette.primary}]}><Ionicons name="cloud-download-outline" size={19} color="#fff"/><Text style={styles.white}>إضافة مع تفعيل الكاش المحلي</Text></Pressable>{services.map(s=><View key={s.id} style={[styles.item,{borderColor:palette.border}]}><Pressable onPress={()=>onChange(services.filter(x=>x.id!==s.id))}><Ionicons name="trash-outline" size={18} color={palette.danger}/></Pressable><Text style={{color:palette.text,flex:1,textAlign:'right'}}>{s.name} · {s.type} · {s.cacheEnabled?'Offline cache':''}</Text></View>)}</View></View></Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},sheet:{borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,padding:18,gap:11},header:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},title:{fontSize:16,fontWeight:'800'},types:{flexDirection:'row',gap:7},type:{borderWidth:1,borderRadius:9,padding:9,flex:1,alignItems:'center'},input:{borderWidth:1,borderRadius:10,padding:10,textAlign:'right'},primary:{borderRadius:11,padding:13,alignItems:'center',justifyContent:'center',flexDirection:'row-reverse',gap:7},white:{color:'#fff',fontWeight:'800'},item:{borderWidth:1,borderRadius:9,padding:9,flexDirection:'row',gap:8,alignItems:'center'}});
